### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by Passenger89** [pzelnip/dotfiles#67]
Apologies if this isn't the right place. Any updates to this toml?

**Comment by pzelnip** [comment]
You mean [`spaceship.toml`](https://github.com/pzelnip/dotfiles/blob/main/.config/starship.toml)?  Nope, haven't updated it in some time.

Was there something specific you were wondering about?

**Comment by Passenger89** [comment]
Ah not anymore. Thank you very much though.
